### PR TITLE
[KCO Recurring] Add ability to set accept header

### PR DESCRIPTION
**Pull request by makasim**

### CODE REVIEW

**Comment by makasim** [comment]
@keis done, rebased on v1.2 and fix tests.

**Comment by keis** [comment]
cool thanks :)

We're still supporting php 5.2 (not running on travis for some reason) so sadly we can't use that nifty ternary short hand.

**Comment by makasim** [comment]
> We're still supporting php 5.2 (not running on travis for some reason) so sadly we can't use that nifty ternary short hand.

ok, I'll remove it

**Comment by makasim** [comment]
@keis done, also rebased and squashed.

**Comment by keis** [comment]
pushing this through our internal process with some minor changes.

**Comment by keis** [comment]
@makasim pushed a v2 please give it a try. changed the name from getAcceptHeader to getAccept to align with the earlier naming.

**Comment by makasim** [comment]
available in https://github.com/klarna/kco_php/releases/tag/v2.0.0

**Pull request closed without merging**
