### PR TITLE
[KCO Recurring][WIP] Add ability to set accept header

### PR DESCRIPTION
**Pull request by makasim**
The content type and accept header are not same for klarna checkout recurring payments.

Looking forward to get your feedback on that.

### CODE REVIEW

**Comment by makasim** [comment]
@keis @RickardDybeck @JoakimLofgren ping

**Comment by keis** [comment]
Hi @makasim thanks for the PR.

Getting this fixed has sadly been on the back burner for a while. Ideally we want to move away from having to change the static field. But I'll see about getting this small patch merged in the interim.

**Comment by makasim** [comment]
@keis I was not still able to do a KCO recurring payment. There was a fatal in your lib. An exception class was not found. I'll look into it and let you know. or may be even provide a fix.

**Comment by makasim** [comment]
Getting fatal when using this sdk as composer package. 

Class 'Klarna_Checkout_ConnectionErrorException' not found in /mnt/www/foo/vendor/klarna/checkout/src/Klarna/Checkout/HTTP/CURLTransport.php on line 147

**Comment by keis** [comment]
What version are you using? I believe that bug was fixed in 1e3d1df447e70e2b (released as part of v1.1.0)

**Comment by makasim** [comment]
@keis master as I think BC break (I added a getAcceptHeader to OrderInterface) must go to master

**Comment by keis** [comment]
We're not actually using the master branch. but rather base changes of the most recent release and merge to appropriate place so in this case we would setup a v2.0 branch.

**Comment by makasim** [comment]
@keis please let me know when you are done with 2.0 branch so I can rebase the PR. thanks.

**Comment by makasim** [comment]
close in favor https://github.com/klarna/kco_php/pull/9. That one opened against v1.2 branch.

**Pull request closed without merging**
